## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('queueing',
                                 ['point-to-point', 'applications', 'internet'])
    obj.source = ['queueing.cc', 'cdf.c']