#!/usr/bin/env bash

cmd=$1
args=$2
# TODO: This seems to solve the error "libstdc++.so.6: version `GLIBCXX_3.4.32' not found"
# But check why this error is popping up now suddenly. Due to gcc 13?
export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
if [[ $1 == "--run" ]];then
	./ns3 run "$2"
elif [[ $1 == "clean" ]];then
	./ns3 clean
elif [[ $1 == "distclean" ]];then
	./ns3 distclean
elif [[ $1 == "build" ]];then
	./ns3 build
elif [[ $1 == "configure" ]];then
	./configure.sh
elif [[ $1 == "" ]];then
	./ns3
else
	echo "This waf script is just a temporary hook for running old bash scripts using waf builder. This does not implement a real waf."
fi
