#!/usr/bin/env bash

cmd=$1
args=$2
if [[ $1 == "--run" ]];then
	./ns3 run "$2"
elif [[ $1 == "clean" ]];then
	./ns3 clean
elif [[ $1 == "distclean" ]];then
	./ns3 distclean
elif [[ $1 == "build" ]];then
	./ns3 build
elif [[ $1 == "configure" ]];then
	echo "Please use configure.sh. Configure with this dummy waf script is not supported since there were many changes to the options naming after waf builder was removed."
elif [[ $1 == "" ]];then
	./ns3
else
	echo "This waf script is just a temporary hook for running old bash scripts using waf builder. This does not implement a real waf."
fi
