mv plots/intervals-incastfct1.pdf plots/fig12a.pdf
mv plots/intervals-longfct1.pdf plots/fig12a.pdf
mv plots/buffer-incastfct-dctcp-.pdf plots/fig11a.pdf
mv plots/buffer-incastfct-powertcp-.pdf plots/fig11b.pdf
mv plots/fcts-nprior.pdf plots/fig10a.pdf
mv plots/buffer-nprior.pdf plots/fig10b.pdf
mv plots/tcp-cubic-incastfct.pdf plots/fig9a.pdf
mv plots/tcp-dctcp-incastfct.pdf plots/fig9b.pdf
mv plots/tcp-timely-incastfct.pdf plots/fig9c.pdf
mv plots/tcp-powertcp-incastfct.pdf plots/fig9d.pdf
mv plots/multi-cubic.pdf plots/fig8a.pdf
mv plots/multi-dctcp.pdf plots/fig8b.pdf
mv plots/multi-thetapowertcp.pdf plots/fig8c.pdf
mv plots/multi-buf99.pdf plots/fig8d.pdf
mv plots/burst-ABM-incastfct.pdf plots/fig7a.pdf
mv plots/burst-ABM-shortfct.pdf plots/fig7b.pdf
mv plots/burst-ABM-buf.pdf plots/fig7c.pdf
mv plots/burst-ABM-th.pdf plots/fig7d.pdf
mv plots/load-ABM-incastfct.pdf plots/fig6a.pdf
mv plots/load-ABM-shortfct.pdf plots/fig6b.pdf
mv plots/load-ABM-buf.pdf plots/fig6c.pdf
mv plots/load-ABM-th.pdf plots/fig6d.pdf